name: End-to-end tests
on: [push]
jobs:
 cypress-run:
   runs-on: ubuntu-latest
   steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Cypress Test
        uses: cypress-io/github-action@v5
        with:
          command: npm run build & npm run dev && npx cypress run
          browser: chrome